# Generated by Django 2.1.5 on 2019-02-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20190202_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='Value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='Value',
            field=models.IntegerField(),
        ),
    ]
