# Generated by Django 2.1.5 on 2019-02-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20190204_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='Date_and_Time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='Date_and_Time',
            field=models.CharField(max_length=30),
        ),
    ]
